// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Munharaunda.Infrastructure.Database;

namespace Munharaunda.Infrastructure.Migrations
{
    [DbContext(typeof(MunharaundaDbContext))]
    [Migration("20210116074829_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Munharaunda.Domain.Models.Funeral", b =>
                {
                    b.Property<int>("FuneralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AddressForFuneral")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DeceasedsProfileNumber")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("FuneralId");

                    b.ToTable("Funeral");

                    b.HasData(
                        new
                        {
                            FuneralId = 1,
                            AddressForFuneral = "15 Albany Crescent Warren Park",
                            Comment = "Test Funeral",
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            DeceasedsProfileNumber = 5,
                            StatusId = 5,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            FuneralId = 2,
                            AddressForFuneral = "15 Albany Crescent Warren Park",
                            Comment = "Test Funeral",
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            DeceasedsProfileNumber = 4,
                            StatusId = 3,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("Munharaunda.Domain.Models.IdentityTypes", b =>
                {
                    b.Property<int>("IdentityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdentityTypeId");

                    b.ToTable("IdentityTypes");

                    b.HasData(
                        new
                        {
                            IdentityTypeId = 1,
                            Description = "Id"
                        },
                        new
                        {
                            IdentityTypeId = 2,
                            Description = "PassPort"
                        });
                });

            modelBuilder.Entity("Munharaunda.Domain.Models.Profile", b =>
                {
                    b.Property<int>("ProfileNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("ActiveDate")
                        .HasColumnType("Date");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Approve1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Approve2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Approve3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Approve4")
                        .HasColumnType("datetime2");

                    b.Property<int>("Approver1")
                        .HasColumnType("int");

                    b.Property<int>("Approver2")
                        .HasColumnType("int");

                    b.Property<int>("Approver3")
                        .HasColumnType("int");

                    b.Property<int>("Approver4")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("Date");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NextOfKin")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("ReOpen")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReOpened")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReOpenedBy")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ProfileNumber");

                    b.ToTable("Profile");

                    b.HasData(
                        new
                        {
                            ProfileNumber = 1,
                            ActiveDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Address = "15 Albany Crescent Parklands CapeTown",
                            Approve1 = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            DateOfBirth = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityNumber = "System",
                            IdentityTypeId = 0,
                            Name = "Alpha",
                            NextOfKin = 0,
                            PhoneNumber = "000000000000",
                            ProfileTypeId = 5,
                            ReOpen = false,
                            ReOpened = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReOpenedBy = 0,
                            Status = 3,
                            Surname = "System",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            ProfileNumber = 2,
                            ActiveDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Address = "15 Albany Crescent Parklands CapeTown",
                            Approve1 = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            DateOfBirth = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityNumber = "System",
                            IdentityTypeId = 0,
                            Name = "Test",
                            NextOfKin = 0,
                            PhoneNumber = "000000000000",
                            ProfileTypeId = 5,
                            ReOpen = false,
                            ReOpened = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReOpenedBy = 0,
                            Status = 3,
                            Surname = "User1",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            ProfileNumber = 3,
                            ActiveDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Address = "15 Albany Crescent Parklands CapeTown",
                            Approve1 = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            DateOfBirth = new DateTime(1982, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityNumber = "MA9XX057XX",
                            IdentityTypeId = 2,
                            Name = "Nicholas",
                            NextOfKin = 0,
                            PhoneNumber = "0846994704",
                            ProfileTypeId = 6,
                            ReOpen = false,
                            ReOpened = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReOpenedBy = 0,
                            Status = 3,
                            Surname = "Namacha",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            ProfileNumber = 4,
                            ActiveDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Address = "15 Albany Crescent Parklands CapeTown",
                            Approve1 = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            DateOfBirth = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityNumber = "System",
                            IdentityTypeId = 0,
                            Name = "Test",
                            NextOfKin = 0,
                            PhoneNumber = "000000000000",
                            ProfileTypeId = 5,
                            ReOpen = false,
                            ReOpened = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReOpenedBy = 0,
                            Status = 3,
                            Surname = "User2",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            ProfileNumber = 5,
                            ActiveDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Address = "15 Albany Crescent Parklands CapeTown",
                            Approve1 = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            DateOfBirth = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityNumber = "System",
                            IdentityTypeId = 0,
                            Name = "Test",
                            NextOfKin = 0,
                            PhoneNumber = "000000000000",
                            ProfileTypeId = 5,
                            ReOpen = false,
                            ReOpened = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReOpenedBy = 0,
                            Status = 5,
                            Surname = "User3",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("Munharaunda.Domain.Models.ProfileTypes", b =>
                {
                    b.Property<int>("ProfileTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileTypeId");

                    b.ToTable("ProfileTypes");

                    b.HasData(
                        new
                        {
                            ProfileTypeId = 1,
                            Description = "Admin"
                        },
                        new
                        {
                            ProfileTypeId = 2,
                            Description = "Member"
                        },
                        new
                        {
                            ProfileTypeId = 3,
                            Description = "NextOfKin"
                        },
                        new
                        {
                            ProfileTypeId = 4,
                            Description = "Dependent"
                        },
                        new
                        {
                            ProfileTypeId = 5,
                            Description = "ColdBody"
                        },
                        new
                        {
                            ProfileTypeId = 6,
                            Description = "Alpha"
                        });
                });

            modelBuilder.Entity("Munharaunda.Domain.Models.Statuses", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Approve1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Approve2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Approve3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Approve4")
                        .HasColumnType("datetime2");

                    b.Property<int>("Approver1")
                        .HasColumnType("int");

                    b.Property<int>("Approver2")
                        .HasColumnType("int");

                    b.Property<int>("Approver3")
                        .HasColumnType("int");

                    b.Property<int>("Approver4")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Approve1 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            StatusDescription = "Terminated",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            StatusId = 2,
                            Approve1 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            StatusDescription = "Pending Authorisation",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            StatusId = 3,
                            Approve1 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            StatusDescription = "Active",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            StatusId = 4,
                            Approve1 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            StatusDescription = "Inarrears",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            StatusId = 5,
                            Approve1 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            StatusDescription = "Closed",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            StatusId = 6,
                            Approve1 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            StatusDescription = "Authorised",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("Munharaunda.Domain.Models.StatusesHistory", b =>
                {
                    b.Property<int>("StatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Approve1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Approve2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Approve3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Approve4")
                        .HasColumnType("datetime2");

                    b.Property<int>("Approver1")
                        .HasColumnType("int");

                    b.Property<int>("Approver2")
                        .HasColumnType("int");

                    b.Property<int>("Approver3")
                        .HasColumnType("int");

                    b.Property<int>("Approver4")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("StatusHistoryId");

                    b.ToTable("StatusesHistory");
                });

            modelBuilder.Entity("Munharaunda.Domain.Models.TransactionCodes", b =>
                {
                    b.Property<int>("TransactionCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Contribution")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("Credit")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("TransactionCodeId");

                    b.ToTable("TransactionCodes");

                    b.HasData(
                        new
                        {
                            TransactionCodeId = 1,
                            Contribution = true,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Credit = true,
                            Description = "Funeral Contribution",
                            Status = 6,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            TransactionCodeId = 2,
                            Contribution = false,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Credit = false,
                            Description = "Funeral Expense",
                            Status = 6,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            TransactionCodeId = 3,
                            Contribution = false,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Credit = true,
                            Description = "Joining Fee",
                            Status = 6,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            TransactionCodeId = 4,
                            Contribution = false,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Credit = true,
                            Description = "Debit Reversal",
                            Status = 6,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            TransactionCodeId = 5,
                            Contribution = false,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Credit = false,
                            Description = "Credit Reversal",
                            Status = 6,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            TransactionCodeId = 6,
                            Contribution = false,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Credit = false,
                            Description = "Joining Fee Reversal",
                            Status = 6,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            TransactionCodeId = 7,
                            Contribution = false,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Credit = true,
                            Description = "Expense Reversal",
                            Status = 6,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            TransactionCodeId = 8,
                            Contribution = false,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Credit = false,
                            Description = "General Expense",
                            Status = 6,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            TransactionCodeId = 9,
                            Contribution = false,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Credit = true,
                            Description = "Deposit",
                            Status = 6,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        },
                        new
                        {
                            TransactionCodeId = 10,
                            Contribution = false,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Credit = true,
                            Description = "Funeral PayOut",
                            Status = 6,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("Munharaunda.Domain.Models.TransactionCodesHistory", b =>
                {
                    b.Property<int>("TransactionCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Contribution")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("Credit")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("TransactionCodeId");

                    b.ToTable("TransactionCodesHistory");
                });

            modelBuilder.Entity("Munharaunda.Domain.Models.Transactions", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Approve1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Approve2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Approve3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Approve4")
                        .HasColumnType("datetime2");

                    b.Property<int>("Approver1")
                        .HasColumnType("int");

                    b.Property<int>("Approver2")
                        .HasColumnType("int");

                    b.Property<int>("Approver3")
                        .HasColumnType("int");

                    b.Property<int>("Approver4")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Contribution")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("FuneralId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TransactionCode")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Amount = 100m,
                            Approve1 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Contribution = true,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 3,
                            FuneralId = 1,
                            Status = 0,
                            TransactionCode = 1
                        },
                        new
                        {
                            TransactionId = 2,
                            Amount = 100m,
                            Approve1 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Contribution = true,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 2,
                            FuneralId = 1,
                            Status = 0,
                            TransactionCode = 1
                        },
                        new
                        {
                            TransactionId = 3,
                            Amount = 100m,
                            Approve1 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Contribution = true,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 3,
                            FuneralId = 1,
                            Status = 0,
                            TransactionCode = 1
                        },
                        new
                        {
                            TransactionId = 4,
                            Amount = 100m,
                            Approve1 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Contribution = true,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 4,
                            FuneralId = 1,
                            Status = 0,
                            TransactionCode = 1
                        },
                        new
                        {
                            TransactionId = 5,
                            Amount = 100m,
                            Approve1 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve2 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve3 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approve4 = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver1 = 0,
                            Approver2 = 0,
                            Approver3 = 0,
                            Approver4 = 0,
                            Contribution = true,
                            Created = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 3,
                            FuneralId = 2,
                            Status = 0,
                            TransactionCode = 1
                        });
                });

            modelBuilder.Entity("Munharaunda.Domain.Models.TransactionsArchive", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Approve1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Approve2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Approve3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Approve4")
                        .HasColumnType("datetime2");

                    b.Property<int>("Approver1")
                        .HasColumnType("int");

                    b.Property<int>("Approver2")
                        .HasColumnType("int");

                    b.Property<int>("Approver3")
                        .HasColumnType("int");

                    b.Property<int>("Approver4")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("FuneralId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TransactionCode")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.ToTable("TransactionsArchive");
                });
#pragma warning restore 612, 618
        }
    }
}
